# Generated by Django 5.2.7 on 2025-11-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'پرداخت در محل')], default='cod', max_length=20),
        ),
    ]
