# Generated by Django 5.2.7 on 2025-11-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_address_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='post_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
