# Generated by RedShop phase 7.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_cancel_tracking_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_released',
            field=models.BooleanField(
                default=False,
                help_text='برای جلوگیری از کم شدن چندباره شمارنده مصرف کوپن استفاده می‌شود.',
                verbose_name='مصرف کوپن آزاد شده',
            ),
        ),
    ]
