# Generated by Django 5.2.16 on 2026-07-13 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_options_alter_orderitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('payment_review_export', 'Payment review CSV export'), ('admin_note', 'Admin note')], max_length=64, verbose_name='عملیات')),
                ('request_id', models.CharField(blank=True, max_length=128, verbose_name='شناسه درخواست')),
                ('message', models.TextField(blank=True, verbose_name='پیام')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='داده تکمیلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر انجام\u200cدهنده')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'لاگ سفارش',
                'verbose_name_plural': 'لاگ\u200cهای سفارش',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='order_audit_action_created_idx'), models.Index(fields=['order', 'created_at'], name='order_audit_order_created_idx')],
            },
        ),
    ]
