# Generated by Django 5.2.7 on 2025-12-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_full_name_address_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='ایمیل'),
        ),
    ]
