"""
Django settings for RedShop project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from django.contrib import staticfiles
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.templatetags.static import static
from .env import env, env_bool, env_int, env_list

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# کلید محرمانه فقط از محیط خوانده می‌شود و نباید داخل سورس ذخیره شود.
SECRET_KEY = env('DJANGO_SECRET_KEY', required=True)

# در توسعه روشن است؛ برای محیط واقعی باید در .env برابر False شود.
DEBUG = env_bool('DJANGO_DEBUG', default=True)

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', default=['127.0.0.1', 'localhost', '[::1]'])


# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",  # فیلترهای پیشرفته
    "unfold.contrib.forms",    # فرم‌های زیبا
    "unfold.contrib.inlines",  # اینلاین‌های مدرن
    "unfold.contrib.import_export", # import-export استفاده
    "unfold.contrib.guardian",      # guardian استفاده می‌کنی
    "unfold.contrib.simple_history", # تاریخچه تغییرات
    "django.contrib.admin",
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.shop.apps.ShopConfig',
    'apps.cart.apps.CartConfig',
    'apps.orders.apps.OrdersConfig',
    'apps.account.apps.AccountConfig',
    'apps.payment.apps.PaymentConfig',
    'apps.coupons.apps.CouponsConfig',
    'apps.compare.apps.CompareConfig',
    'easy_thumbnails',
    'mptt',
    'django_jalali',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'RedShop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'shop/templates',
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.cart.context_processors.cart',
                'apps.shop.context_processors.common_data',
            ],
        },
    },
]

WSGI_APPLICATION = 'RedShop.wsgi.application'


# Database
# مقدارها از .env خوانده می‌شوند تا رمز دیتابیس داخل سورس نماند.
DATABASES = {
    'default': {
        'ENGINE': env('DB_ENGINE', default='django.db.backends.postgresql'),
        'NAME': env('DB_NAME', default='redshop_db'),
        'USER': env('DB_USER', default='redshop_user'),
        'PASSWORD': env('DB_PASSWORD', default=''),
        'HOST': env('DB_HOST', default='localhost'),
        'PORT': env('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


AUTH_USER_MODEL = 'account.ShopUser'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/images/'
MEDIA_ROOT = BASE_DIR / 'images'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/account/login/'
LOGIN_REDIRECT_URL = '/account/profile/'
LOGOUT_REDIRECT_URL = '/'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


# Zarinpal Settings
# در توسعه از سندباکس استفاده می‌شود. مقدارهای واقعی فقط در .env نگهداری می‌شوند.
ZARINPAL_MERCHANT_ID = env('ZARINPAL_MERCHANT_ID', default='00000000-0000-0000-0000-000000000000')
ZARINPAL_BROKER = env('ZARINPAL_BROKER', default='https://sandbox.zarinpal.com/pg/v4/payment/')
ZARINPAL_REQUEST_URL = f"{ZARINPAL_BROKER}request.json"
ZARINPAL_VERIFY_URL = f"{ZARINPAL_BROKER}verify.json"
ZARINPAL_START_PAY_URL = env('ZARINPAL_START_PAY_URL', default='https://sandbox.zarinpal.com/pg/StartPay/')
ZARINPAL_CALLBACK_URL = env('ZARINPAL_CALLBACK_URL', default='http://127.0.0.1:8000/payment/verify/')


# Email Configuration
# رمز SMTP نباید داخل سورس ذخیره شود. در توسعه می‌توان از Console Backend استفاده کرد.
EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env_int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER or 'webmaster@localhost')

# تنظیمات پایه امنیتی برای کوکی‌ها. مقدارهای سخت‌گیرانه در زمان دیپلوی فعال می‌شوند.
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', default=not DEBUG)
SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', default=False)
SECURE_HSTS_SECONDS = env_int('SECURE_HSTS_SECONDS', default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False)
SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', default=False)
SECURE_CONTENT_TYPE_NOSNIFF = True


UNFOLD = {
    "SITE_TITLE": "مدیریت فروشگاه ردشاپ",
    "SITE_HEADER": "RedShop Admin",
    "SITE_URL": "/",
    "SITE_ICON": {
            "light": lambda request: static("images/logo-dark.png"),  # آدرس لوگو
            "dark": lambda request: static("images/logo-light.png"),
        },

    "DASHBOARD_CALLBACK": "RedShop.dashboard.dashboard_callback",

    "STYLES": [
        lambda request: static("css/unfold_rtl_fix.css"),
    ],
    "SCRIPTS": [],
    "COLORS": {
        "primary": {
            "50": "239 246 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
        },
    },

    # گروه‌بندی منوی سمت راست (Sidebar)
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,

        "navigation": [

            {
                "title": "سفارشات و مالی",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "سفارش‌ها",
                        "icon": "shopping_cart",  # آیکون سبد
                        "link": reverse_lazy("admin:orders_order_changelist"),
                    },
                    {
                        "title": "تراکنش‌ها",
                        "icon": "receipt_long",  # آیکون فاکتور
                        "link": reverse_lazy("admin:orders_transaction_changelist"),
                    },
                    {
                        "title": "کدهای تخفیف",
                        "icon": "local_offer",
                        "link": reverse_lazy("admin:coupons_coupon_changelist"),
                    },
                ],
            },

            {
                "title": "مدیریت فروشگاه",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "محصولات",
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:shop_product_changelist"),
                    },
                    {
                        "title": "دسته‌بندی‌ها",
                        "icon": "category",
                        "link": reverse_lazy("admin:shop_category_changelist"),
                    },
                    {
                        "title": "برندها",
                        "icon": "branding_watermark",
                        "link": reverse_lazy("admin:shop_brand_changelist"),
                    },
                    {
                        "title": "ویژگی‌های پویا",
                        "icon": "tune",
                        "link": reverse_lazy("admin:shop_categoryfeature_changelist"),
                    },
                ],
            },

            {
                "title": "کاربران و تعاملات",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "لیست کاربران",
                        "icon": "group",
                        "link": reverse_lazy("admin:account_shopuser_changelist"),
                    },
                    {
                        "title": "نظرات کاربران",
                        "icon": "rate_review",
                        "link": reverse_lazy("admin:shop_productcomment_changelist"),
                    },
                ],
            },
        ],
    },
}

# --- RedShop logging configuration ---

LOG_LEVEL = env("DJANGO_LOG_LEVEL", default="INFO").upper()
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {
            "format": "[{levelname}] {name}: {message}",
            "style": "{",
        },
        "verbose": {
            "format": "[{asctime}] {levelname} {name} {module}:{lineno} - {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
            "level": LOG_LEVEL,
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "redshop.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "encoding": "utf-8",
            "formatter": "verbose",
            "level": LOG_LEVEL,
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": env("DJANGO_LOG_LEVEL_DJANGO", default="INFO").upper(),
            "propagate": True,
        },
        "django.request": {
            "handlers": ["console", "file"],
            "level": "ERROR",
            "propagate": False,
        },
        "apps": {
            "handlers": ["console", "file"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}

# --- End RedShop logging configuration ---
