"""
Django settings for RedShop project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from django.contrib import staticfiles
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.templatetags.static import static

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3g6vg4z#1u!+my8t&1w^sclizr=yvc$c&meqgrk&-&1e2(tqef'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",  # فیلترهای پیشرفته
    "unfold.contrib.forms",    # فرم‌های زیبا
    "unfold.contrib.inlines",  # اینلاین‌های مدرن
    "unfold.contrib.import_export", # import-export استفاده
    "unfold.contrib.guardian",      # guardian استفاده می‌کنی
    "unfold.contrib.simple_history", # تاریخچه تغییرات
    "django.contrib.admin",
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop.apps.ShopConfig',
    'cart.apps.CartConfig',
    'orders.apps.OrdersConfig',
    'account.apps.AccountConfig',
    'payment.apps.PaymentConfig',
    'coupons.apps.CouponsConfig',
    'compare.apps.CompareConfig',
    'easy_thumbnails',
    'mptt',
    'django_jalali',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'RedShop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'shop/templates',
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
                'shop.context_processors.common_data',
            ],
        },
    },
]

WSGI_APPLICATION = 'RedShop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'redshop_db',
        'USER': 'redshop_user',
        'PASSWORD': '12345',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True


AUTH_USER_MODEL = 'account.ShopUser'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/images/'
MEDIA_ROOT = BASE_DIR / 'images'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/account/login/'
LOGIN_REDIRECT_URL = '/account/profile/'
LOGOUT_REDIRECT_URL = '/'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


# Zarinpal Settings (Sandbox)
ZARINPAL_MERCHANT_ID = "00000000-0000-0000-0000-000000000000"  # کد مخصوص سندباکس
ZARINPAL_BROKER = "https://sandbox.zarinpal.com/pg/v4/payment/"
ZARINPAL_REQUEST_URL = f"{ZARINPAL_BROKER}request.json"
ZARINPAL_VERIFY_URL = f"{ZARINPAL_BROKER}verify.json"
ZARINPAL_START_PAY_URL = "https://sandbox.zarinpal.com/pg/StartPay/"
ZARINPAL_CALLBACK_URL = "http://127.0.0.1:8000/payment/verify/"  # آدرس بازگشت


# Email Configuration (SMTP - Gmail)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True  # پروتکل امنیتی گوگل

EMAIL_HOST_USER = 'pythonnazarian@gmail.com'

EMAIL_HOST_PASSWORD = 'araxhmssntiwefhq'



UNFOLD = {
    "SITE_TITLE": "مدیریت فروشگاه ردشاپ",
    "SITE_HEADER": "RedShop Admin",
    "SITE_URL": "/",
    "SITE_ICON": {
            "light": lambda request: static("images/logo-dark.png"),  # آدرس لوگو
            "dark": lambda request: static("images/logo-light.png"),
        },

    "DASHBOARD_CALLBACK": "RedShop.dashboard.dashboard_callback",

    "STYLES": [
        lambda request: static("css/unfold_rtl_fix.css"),
    ],
    "SCRIPTS": [],
    "COLORS": {
        "primary": {
            "50": "239 246 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
        },
    },

    # گروه‌بندی منوی سمت راست (Sidebar)
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,

        "navigation": [

            {
                "title": "سفارشات و مالی",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "سفارش‌ها",
                        "icon": "shopping_cart",  # آیکون سبد
                        "link": reverse_lazy("admin:orders_order_changelist"),
                    },
                    {
                        "title": "تراکنش‌ها",
                        "icon": "receipt_long",  # آیکون فاکتور
                        "link": reverse_lazy("admin:orders_transaction_changelist"),
                    },
                    {
                        "title": "کدهای تخفیف",
                        "icon": "local_offer",
                        "link": reverse_lazy("admin:coupons_coupon_changelist"),
                    },
                ],
            },

            {
                "title": "مدیریت فروشگاه",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "محصولات",
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:shop_product_changelist"),
                    },
                    {
                        "title": "دسته‌بندی‌ها",
                        "icon": "category",
                        "link": reverse_lazy("admin:shop_category_changelist"),
                    },
                    {
                        "title": "برندها",
                        "icon": "branding_watermark",
                        "link": reverse_lazy("admin:shop_brand_changelist"),
                    },
                    {
                        "title": "ویژگی‌های پویا",
                        "icon": "tune",
                        "link": reverse_lazy("admin:shop_categoryfeature_changelist"),
                    },
                ],
            },

            {
                "title": "کاربران و تعاملات",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "لیست کاربران",
                        "icon": "group",
                        "link": reverse_lazy("admin:account_shopuser_changelist"),
                    },
                    {
                        "title": "نظرات کاربران",
                        "icon": "rate_review",
                        "link": reverse_lazy("admin:shop_productcomment_changelist"),
                    },
                ],
            },
        ],
    },
}