# Generated by RedShop phase 7.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='اگر خالی باشد، محدودیت تعداد مصرف ندارد.',
                null=True,
                verbose_name='سقف تعداد مصرف',
            ),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد مصرف‌شده'),
        ),
    ]
