# Generated by Django 5.2.7 on 2025-11-04 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_categoryfeature_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryfeature',
            options={'ordering': ['created'], 'verbose_name': 'ویژگی دسته', 'verbose_name_plural': 'ویژگی\u200cهای دسته'},
        ),
        migrations.RemoveField(
            model_name='categoryfeature',
            name='ordering',
        ),
        migrations.AddField(
            model_name='categoryfeature',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='زمان ایجاد'),
            preserve_default=False,
        ),
    ]
