# Generated by Django 5.2.7 on 2025-11-12 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_categoryfeature_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryfeature',
            options={'ordering': ['created'], 'verbose_name': 'ویژگی دسته', 'verbose_name_plural': 'ویژگی\u200cهای دسته'},
        ),
    ]
