# Generated by Django 5.2.7 on 2025-11-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_category_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='تصویر دسته بندی'),
        ),
    ]
