# Generated by Django 5.2.7 on 2025-11-18 21:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='نام خانوادگی گیرنده'),
            preserve_default=False,
        ),
    ]
