# Generated by Django 5.2.7 on 2025-11-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='About_the_company',
            field=models.TextField(default=0, max_length=6500, verbose_name='درباره کمپانی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='established',
            field=models.CharField(default=None, max_length=100, verbose_name='زمان تاسیس'),
            preserve_default=False,
        ),
    ]
