# Generated by Django 5.2.7 on 2025-11-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_categoryfeature_productfeaturevalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryfeature',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='واحد'),
        ),
    ]
