# Generated by Django 5.2.7 on 2025-11-03 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_categoryfeature_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryfeature',
            options={'verbose_name': 'ویژگی دسته', 'verbose_name_plural': 'ویژگی\u200cهای دسته'},
        ),
        migrations.RemoveField(
            model_name='categoryfeature',
            name='unit',
        ),
        migrations.AlterField(
            model_name='categoryfeature',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_features', to='shop.category', verbose_name='دسته'),
        ),
        migrations.AlterField(
            model_name='categoryfeature',
            name='name',
            field=models.CharField(max_length=250, verbose_name='نام ویژگی'),
        ),
    ]
