# Generated by Django 5.2.7 on 2025-11-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_categoryfeature_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryfeature',
            options={'ordering': ['ordering', 'name'], 'verbose_name': 'ویژگی دسته', 'verbose_name_plural': 'ویژگی\u200cهای دسته'},
        ),
        migrations.AddField(
            model_name='categoryfeature',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
    ]
