# Generated by Django 5.2.7 on 2025-11-12 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryfeature',
            options={'ordering': ['group', 'id'], 'verbose_name': 'ویژگی دسته', 'verbose_name_plural': 'ویژگی\u200cهای دسته'},
        ),
        migrations.CreateModel(
            name='FeatureGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام گروه ویژگی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_groups', to='shop.category', verbose_name='دسته')),
            ],
            options={
                'verbose_name': 'گروه ویژگی',
                'verbose_name_plural': 'گروه\u200cهای ویژگی',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='categoryfeature',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features', to='shop.featuregroup', verbose_name='گروه ویژگی'),
        ),
    ]
