# Generated by Django 5.2.7 on 2025-11-12 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_categoryfeature_options_featuregroup_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryfeature',
            options={'ordering': ['group', 'created'], 'verbose_name': 'ویژگی دسته', 'verbose_name_plural': 'ویژگی\u200cهای دسته'},
        ),
    ]
