# Generated by Django 5.2.7 on 2025-11-14 10:35

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_categoryfeature_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[500, 500], upload_to='category_images/', verbose_name='تصویر دسته بندی'),
        ),
    ]
