# Generated by Django 5.2.7 on 2025-11-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_category_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['created'], 'verbose_name': 'تصویر', 'verbose_name_plural': 'تصویر ها'},
        ),
        migrations.RemoveIndex(
            model_name='image',
            name='shop_image_created_9f3f47_idx',
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['created'], name='shop_image_created_6a3b1a_idx'),
        ),
    ]
