# Generated by Django 5.2.7 on 2025-11-29 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_category_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, 'خیلی بد'), (2, 'بد'), (3, 'معمولی'), (4, 'خوب'), (5, 'عالی')], default=5, verbose_name='امتیاز')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('suggest', models.BooleanField(default=True, help_text='آیا خرید این کالا را پیشنهاد می\u200cکنید؟', verbose_name='پیشنهاد خرید')),
                ('active', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر کاربر',
                'verbose_name_plural': 'نظرات کاربران',
                'ordering': ['-created'],
            },
        ),
    ]
