# Generated by Django 5.2.7 on 2025-11-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_productcomment_suggest_commentlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentlike',
            options={'verbose_name': 'واکنش به نظر', 'verbose_name_plural': 'واکنش\u200cهای کاربران'},
        ),
        migrations.AddField(
            model_name='commentlike',
            name='status',
            field=models.BooleanField(choices=[(True, 'لایک'), (False, 'دیس\u200cلایک')], default=True),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='suggest',
            field=models.CharField(choices=[('yes', 'پیشنهاد می\u200cکنم'), ('no', 'پیشنهاد نمی\u200cکنم'), ('none', 'نظری ندارم')], default='none', max_length=10, verbose_name='پیشنهاد خرید'),
        ),
    ]
