# Generated by Django 5.2.16 on 2026-07-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_productfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=6500, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='off',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='تخفیف'),
        ),
    ]
