# Generated by Django 5.2.7 on 2025-11-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_line',
            field=models.TextField(blank=True, null=True),
        ),
    ]
