# Generated by Django 5.2.9 on 2025-12-03 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_transaction_ref_id'),
        ('shop', '0020_productfavorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'آیتم سفارش', 'verbose_name_plural': 'آیتم\u200cهای سفارش'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'تراکنش', 'verbose_name_plural': 'تراکنش\u200cها'},
        ),
        migrations.AlterField(
            model_name='order',
            name='address_line',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس کامل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='شماره سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'پرداخت در محل'), ('online', 'درگاه بانکی')], default='cod', max_length=20, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='post_price',
            field=models.PositiveIntegerField(default=0, verbose_name='هزینه پست'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_price',
            field=models.PositiveIntegerField(default=0, verbose_name='هزینه حمل و نقل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت/تایید'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('canceled', 'لغو شده'), ('refunded', 'مرجوع شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت کل'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='weight',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='وزن محصول'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='مبلغ (تومان)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='provider',
            field=models.CharField(default='cod', max_length=50, verbose_name='درگاه پرداخت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='raw_response',
            field=models.JSONField(blank=True, null=True, verbose_name='پاسخ خام بانک'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ref_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کد پیگیری (RefID)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='success',
            field=models.BooleanField(default=False, verbose_name='موفق'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه تراکنش (Authority)'),
        ),
    ]
